### ISSUE TITLE
Could to-inst coerce more date/time formats?

### ISSUE THREAD

**Issue by seancorfield** [exoscale/coax#11]
We're looking to deprecate our https://github.com/worldsingles/web-specs library in favor of Coax and we're starting to pick apart coercion from validation in our code (that web-specs library has Specs that use `s/conformer` to do the coercion as part of the "validation", which is not considered to be "best practice").

Because of the input data we are dealing with, our date/time coercion accepts quite a few different formats -- see https://github.com/worldsingles/web-specs/blob/master/src/ws/web/spec.clj#L56-L59

I see that Coax's `to-inst` delegates to `clojure.instant/read-instant-date` which only accepts RFC-3339 format strings.

Would you be open to a pull request that accepted additional string formats if the RFC-3339 parse fails?

**Comment by mpenet** [comment]
Sorry about the late reply, for some reason I didn't get any notification about the issue being created. 

It's intentionally minimal by default; trying to parse N times every inst? would be quite wasteful as a default.

I think in your case you might either want to register a separate date spec for it with a qualified-keyword and then set a custom coercer globally with `coax/def` or you can also do that via `coerce` options, overriding `inst?`. 
Alternatively you *could* modify the coercer default for `inst?` in `exoscale.coax/registry-ref`, it's a bit dirty but that's also a possibility if you don't want to rely on coerce options.

**Comment by seancorfield** [comment]
Going the `c/def` route for a global coercer would probably work well enough for our needs. As a library maintainer myself, I certainly understand the "minimal by default" design intentions! 😄
