### ISSUE TITLE
macrovich is a dev-only dependency so "compile all" doesn't work on the published JAR

### ISSUE THREAD

**Issue by seancorfield** [exoscale/coax#22]
As a sanity check on code at work, we use `athos/clj-check` to compile all code (and highlight reflection warnings etc). Since the addition of `macrovich` to `coax`, that check fails because the published JAR doesn't specify `macrovich` as a dependency in `pom.xml` -- because it is dev-only.

Using `coax` directly in source code doesn't seem to break, however, which surprises me a bit.

I commented on the commit that added `macrovich` to note that I'd worked to _remove_ that dependency from my `.cljc` projects, and I would certainly _prefer_ that `coax` didn't drag it back in.

**Comment by mpenet** [comment]
alpha18 is without macrovich fyi
